name: Scheduled Retraining

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * 1' 

permissions:
  contents: write 

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'

    - name: Run DVC pipeline
      env:
        ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }} 
      run: |
        echo "Running DVC pipeline with API key..."
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        dvc repro

    - name: Commit and push changes
      run: |
        # Check if there are changes to commit
        if [[ -n $(git status -s) ]]; then
          git add .
          git commit -m "Automated model retraining"
          git push
        else
          echo "No changes to commit."
        fi 
